name: CI/CD Pipeline - Task Manager

# Se ejecuta en cada push a la rama main o en cada pull request a main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --- JOB 1: Ejecutar los tests ---
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar tests unitarios
      run: python -m unittest discover -s task_manager/tests

  # --- JOB 2: Construir y publicar la imagen Docker ---
  build-and-push:
    # Este job solo se ejecuta si el job 'test' ha terminado correctamente
    needs: test
    
    # Solo se ejecuta en la rama 'main', para no publicar imágenes de pull requests
    if: github.ref == 'refs/heads/main'
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Login a Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Construir y publicar imagen Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: davescusope/task-manager:latest